## 1. Headers and Imports

In [2]:
import tensorflow as tf

In [2]:
tf.config.list_physical_devices(device_type=None)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## 2. Initializations

In [8]:
variable_type = tf.Variable(1)
print(variable_type)

constant_type = tf.constant(2)
print(constant_type)

diagonal_type = tf.eye(3)
print(diagonal_type)

ones_type = tf.ones((2,3))
print(ones_type)

zeros_type = tf.zeros((2,3))
print(zeros_type)

range_of_num = tf.range(10)
print(range_of_num)

random_num = tf.random.normal((2, 3))
print(random_num)

# Slicing
print(random_num[1,1:3])

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[-1.3544159   0.7045493   0.03666191]
 [ 0.86918795  0.43842277 -0.53439844]], shape=(2, 3), dtype=float32)
tf.Tensor([ 0.43842277 -0.53439844], shape=(2,), dtype=float32)


## 3. Reassignment
- In general Tensors cant be reassigned after defining them
- To reassign them in the same **memory**, we use tf.compat.v1.assign command

In [16]:
new_var = tf.Variable(ones_type)
ones_type = tf.compat.v1.assign(new_var,zeros_type, validate_shape=None, use_locking=None, name=None)
print(ones_type)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


## 4. Math

In [25]:
add_val = variable_type + constant_type
print(add_val)

sub_val = variable_type - constant_type
print(sub_val)

mul_val = variable_type * constant_type
print(mul_val)

div_val = variable_type / constant_type
print(div_val)

reminder_val = variable_type % constant_type
print(reminder_val)

power_val = variable_type**constant_type
print(power_val)

math_exp_val = tf.math.exp(2.0)
print(math_exp_val)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(7.3890557, shape=(), dtype=float32)


## 5. BroadCasting

In [27]:
random_num = tf.random.normal((2, 3))
print(random_num)

random_num_new = random_num+2
print(random_num_new)

tf.Tensor(
[[-1.3544159   0.7045493   0.03666191]
 [ 0.86918795  0.43842277 -0.53439844]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.6455841 2.7045493 2.0366619]
 [2.8691878 2.4384227 1.4656016]], shape=(2, 3), dtype=float32)


## 6. Matrix Operations

In [18]:
x = tf.constant([[1, 3],[9, 7]])
y = tf.constant([[1, 3],[5, 7]])

dot_val = tf.tensordot(x,y,axes = 1)
print(dot_val)

mat_mul = tf.matmul(x,y)
print(mat_mul)

mat_mul_2 = x@y
print(mat_mul_2)

mat_mul_reshaped = tf.reshape(mat_mul, (1,4))
print(mat_mul_reshaped)

mat_mul_transposed = tf.transpose(mat_mul)
print(mat_mul_transposed)

tf.Tensor(
[[16 24]
 [44 76]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16 24]
 [44 76]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16 24]
 [44 76]], shape=(2, 2), dtype=int32)
tf.Tensor([[16 24 44 76]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[16 44]
 [24 76]], shape=(2, 2), dtype=int32)


## 7. Slicing, Shuffling, Batching, Repeat
- The reason for using repeat is During batching, incase of batchsize which doesnt equally divide dataset, it would use the dataset again to fill gaps
- Dont Know Why i am not able to see data, mayble its because i have to run the session. Need to look at this

In [66]:
x = tf.random.normal((10,3))
y = tf.random.uniform((10,1))
dataset = tf.data.Dataset.from_tensor_slices((x,y))

shuffled_data = dataset.shuffle(1000).repeat()
batch_data = shuffled_data.batch(200)

print(batch_data)

<BatchDataset element_spec=(TensorSpec(shape=(None, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


## 8. Gradients

In [77]:
with tf.GradientTape() as tape:
    tape.watch(x)
    new_y = tf.math.exp(x*2)
gradient_data = tape.gradient(new_y,x)

print(new_y)
print(gradient_data)

tf.Tensor(
[[6.6614576e-02 4.0922651e+00 1.0760789e+00]
 [5.6880975e+00 2.4033065e+00 3.4342140e-01]
 [8.5709554e-01 2.2910820e+01 8.1671178e-01]
 [5.7752991e-01 1.7131725e+01 1.2452147e+01]
 [4.1777250e-01 1.9706668e-02 8.7893027e-01]
 [1.2079237e-01 7.4173884e+00 3.8459759e+00]
 [1.1499909e+00 5.9869766e-02 7.8123426e+00]
 [1.7497662e+00 9.7340101e-01 4.0059349e+01]
 [6.9672627e+00 1.2892772e-01 2.7012116e-01]
 [5.5168635e-01 7.0787035e-02 1.7783983e+00]], shape=(10, 3), dtype=float32)
tf.Tensor(
[[1.33229151e-01 8.18453026e+00 2.15215778e+00]
 [1.13761950e+01 4.80661297e+00 6.86842799e-01]
 [1.71419108e+00 4.58216400e+01 1.63342357e+00]
 [1.15505981e+00 3.42634506e+01 2.49042931e+01]
 [8.35545003e-01 3.94133367e-02 1.75786054e+00]
 [2.41584733e-01 1.48347769e+01 7.69195175e+00]
 [2.29998183e+00 1.19739532e-01 1.56246853e+01]
 [3.49953246e+00 1.94680202e+00 8.01186981e+01]
 [1.39345255e+01 2.57855445e-01 5.40242314e-01]
 [1.10337269e+00 1.41574070e-01 3.55679655e+00]], shape=(10, 3),

## 9. References
1. https://lyhue1991.github.io/eat_tensorflow2_in_30_days/
2. https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/TensorFlow/Basics/tutorial3-neuralnetwork.py